[deploy]
bucket = 'cruddur-cfn-artifacts'
region = 'eu-central-1'
stack_name = 'CrdSrvBackendFlask'


[parameters]
EnvFrontendUrl = 'https://felix-cloudcamp.com'
EnvBackendUrl = 'https://api.felix-cloudcamp.com'