# NON MULTI (DEV) EXAMPLE 
version: "3.8"
services:
  frontend-react-js:
    container_name: app-dev
    image: app-dev
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
    build: 
      context: ./frontend-react-js
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js

networks: 
  internal-network:
    driver: bridge
    name: cruddur


